application: same-page
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static/
  
- url: /share
  static_dir: static/js/share/
  
- url: /channel
  static_dir: static/js/channel/
  
- url: /.*
  script: main.app
  
- url: /index\.html
  script: main.app
  
libraries:
- name: jinja2
  version: latest







